sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - chmod +x setup.sh
  - ./setup.sh
branches:
  only:
    - master
script: pytest --cov
after_success:
  - coveralls